 apiVersion: kustomize.toolkit.fluxcd.io/v1
 kind: Kustomization
 metadata:
   name: sops-secrets
   namespace: flux-system
 spec:
   decryption:
     provider: sops
     secretRef:
       name: sops-age
   force: false
   interval: 10m0s
   path: ./apps/
   prune: true
   sourceRef:
     kind: GitRepository
     name: flux-system
